name: CodexMain
version: 1.0
main: org.codex.factions.FactionsMain
description: A modern solution to an old problem
api-version: 1.8.8
commands:
  f:
        aliases: [faction, fac]
        description: Master command for Faction plugin..
  givechunkbuster: 
        aliases: [gbuster, gchunkbuster, gbust]
        description: Gives a Player a Chunk Buster.
  enchanter:
        aliases: [openenchanter]
        description: Opens Enchanter
  giveenergy:
        aliases: [addenergy]
        description: Gives the Player Energy.
  giveset:
        aliases: [gset]
        description: Gives custom Armor to executor.
  givebook:
        aliases: [gbook]
        description: Gives a Book
  givedust:
        aliases: [gdust, idust]
        description: Gives Dust
  fix:
        description: Fixes an Item in your Inventory.
  rename:
        aliases: [name]
        description: Renames an Item in Players Hand.
  harvesters:
        aliases: [harvest, h]
        description: Shows Harvesters.
  giveenergyharvester:
        aliases: [giveharvester, gharvester, gharv]
        description: Gives Harvesters.
        usage: /gharv [TYPE]
  removeharvester:
        aliases: [rharvester, rharv]
        description: Removes a Harvester from the registry.
        usage: /rharv [ID]
  giveitem:
        aliases: [gitem, spawnitem, sitem, si]
        description: Gives the Player a custom Item.
        usage: /giveitem [ITEM]
  cenchant:
        aliases: [customenchant, enchantc]
        description: Gives a Custom Enchant.
  world:
        aliases: [wrld, wld, worldmanager, wrldmngr]
        description: The master command for your Worlds.
  ah:
        aliases: [auctionhouse, auc]
        description: Main command to use auction house features.
  eco: 
        aliases: [economy, ecomanager]
        description: The economy systems master command.
  pay:
        description: Pays a Player.
  wild:
        aliases: [wilderness, wildtp, wild tp]
        description: Teleports you to random location.
  balance:
        aliases: [bal, checkbalance]
        description: Used to check a Players Balance.
  block36:
        description: Gives the Player a custom Raiding Block.